Use crypto.diffieHellman to derive secret if available
digitalbazaar/minimal-cipher pull request #26
Opened 2020-08-19 22:47 UTC by mattcollier

2020-08-19 22:53 UTC, aljones15 approved these changes
I don't totally understand what is happening here, but if we are not using nacl all the time and instead using a node crypto method that seems fine. I am assuming the es2020 syntax has been tested when used in other projects? What version of nodeJs does this require?

this spec is involved with this?
https://tools.ietf.org/html/rfc3526

2020-08-19 23:01 UTC, mattcollier commented
@aljones15 Turns out that converting an Ed25519 key into a X25519 key is computationally expensive and slow.  It also happens that Node.js recently landed a native implementation we can use for this.  So, we use native code when available, otherwise, fall back to using nacl.

There's a comment that states that the `diffieHelman` API (not to be confused with the `DiffieHellman` class was added in 13.x).  If the API is present, it will be used, if not nacl will be used.

Dynamic imports, the ES2020 feature in question, are supported in both node 13 and 14 which means the existing check for the `crypto.diffieHelman` API should be adequate to also ensure that dynamic imports are available.

2020-08-20 02:18 UTC, dlongley requested changes
I think we shouldn't add `env` to this project -- at least not in the way it's being used here. I'll take on switching this over to use the existing pattern.

2020-08-20 02:18 UTC, dlongley commented on EncryptTransformer.js
```suggestion
```

2020-08-20 02:18 UTC, dlongley commented on DecryptTransformer.js
```suggestion
```

2020-08-20 02:18 UTC, dlongley commented on Cipher.js
```suggestion
```

2020-08-20 02:21 UTC, dlongley commented
In fact, I get this error when trying to run the karma tests locally:

```
ERROR in ../algorithms/diffieHellman.js
Module not found: Error: Can't resolve 'crypto' in '../minimal-cipher/algorithms'
 @ ../algorithms/diffieHellman.js 20:25-41 49:25-41 72:31-47
```

I'm not sure why they are passing here. I'm going to switch things over and see if they pass locally.

2020-08-20 02:42 UTC, dlongley approved these changes
Applied changes to remove `env.js`. Solves the test-karma issue as well. LGTM now. Thanks, @mattcollier!

2020-08-20 02:42 UTC, dlongley commented on .eslintrc.js
> +    ecmaVersion: 2020
If this was only for the dynamic import, we can remove now.

2020-08-20 02:47 UTC, dlongley commented
@mattcollier - If you're ok with the changes I made above then, IMO, this is ready for merge and release.

2020-08-20 12:37 UTC, merged